 - name: SonarScanner.NET
      uses: highbyte/sonarscan-dotnet@v2.5.0
      with:
        # The key of the SonarQube project
        sonarProjectKey: YAFNET_YAFNET
        # The name of the SonarQube project
        sonarProjectName:  yafnet
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
        sonarOrganization: yafnet
        dotnetBuildArguments: ./yafsrc
        
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
